function [P,X,Y,Z,PHI,THETA]=genPSFHE(N)
%GENPSFHE Generate PSF of high energy telescope from PSFs generated by
%genPSFClmt.

% 90, rectangular x 2:
[P0,X,Y,Z,PHI,THETA]=genPSFClmt(N,0);

% 90, square:
[P1,~,~,~,~,~]=genPSFClmt(N,1);

% -150, rectangular x 3:
P00=getResp(P0,PHI,THETA,[1/2,sqrt(3)/2,0,0],PHI,THETA);

% 150, rectangular x 4:
P01=getResp(P0,PHI,THETA,[sqrt(3)/2,1/2,0,0],PHI,THETA);

% -90, rectangular x 3:
P02=getResp(P0,PHI,THETA,[0,1,0,0],PHI,THETA);

% -30, rectangular x 1:
P03=getResp(P0,PHI,THETA,[1/2,-sqrt(3)/2,0,0],PHI,THETA);

% 30, rectangular x 2:
P04=getResp(P0,PHI,THETA,[sqrt(3)/2,-1/2,0,0],PHI,THETA);

% -30, square x 1:
P10=getResp(P1,PHI,THETA,[1/2,-sqrt(3)/2,0,0],PHI,THETA);

% 30, square x 1:
P11=getResp(P1,PHI,THETA,[sqrt(3)/2,-1/2,0,0],PHI,THETA);

P=(P0*2+P00*3+P01*4+P02*3+P03*1+P04*2+P10+P11)/17;

% normalize PSF
% P=P/max(P(:));
return