function Z=list2map(XList,YList,ZList,X,Y,undef)
%LIST2MAP convert data list into map.
% undefined data on the generated map is set to undef.
% X and Y must be monotonic (as if generated by meshgrid).

if isempty(undef)
    undef=0;
end

Z=zeros(size(X));
isdefined=zeros(size(X));
L=length(XList);

h=waitbar(0,'Please wait...');
if ismonotonic(X,1e-8) && ismonotonic(Y,1e-8)
    dx=mean(mean(diff(X,1,2)));
    dy=mean(mean(diff(Y,1,1)));
    for l=1:L
        idy=round((YList(l)-Y(1,1))/dy)+1;
        idx=round((XList(l)-X(1,1))/dx)+1;
        isdefined(idy,idx)=1;
        Z(idy,idx)=Z(idy,idx)+ZList(l);
        waitbar(l/L)
    end
else
    for l=1:L
        s=(X-XList(l)).^2+(Y-YList(l)).^2;
        [~,idy]=min(min(s,[],2));
        [~,idx]=min(min(s,[],1));
        isdefined(idy,idx)=1;
        Z(idy,idx)=Z(idy,idx)+ZList(l);
        waitbar(l/L)
    end
end
close(h)
Z=Z+(1-isdefined)*undef;
return